version: "2"
services:
 web:
  container_name: emd-web-server
  image: zzglider/emd2024:Abr12
  ports:
    - "28000:28000"
  depends_on:
    - mongo
  links:
    - mongo
 mongo:
  container_name: mongo-server
  image: mongo
